### ISSUE TITLE
Taking screenshot on active window only

### ISSUE THREAD

**Issue by mdenadal** [boweeble/s3d-thumbnail-generator#1]
Really a nice job !!

Can I ask you why the application doesn't take the screenshot limiting to active window only?
IMHO working only with maximized window is somehow limiting.

**Comment by boweeble** [comment]
The app does work in this manner (active window), however the default settings allow a quick and easy setup. It's quite difficult to determine where the appropriate place to generate the thumbnail will be if the app isn't maximized. 

If you have suggestions on how to achieve this I'm open to them.
