### ISSUE TITLE
DOES NOT WORK WITH KLIPPER/MAINSAIL

### ISSUE THREAD

**Issue by screech24** [boweeble/s3d-thumbnail-generator#2]
Hello, I tried to install this and use it with Klipper/ Mainsail but the link you have provided in Step 5 is not for use with S3D it is specifically a plugin built for CURA and has nothing to do with S3D. https://github.com/emtrax-ltd/Cura2MoonrakerPlugin

Also just wanted to point out that I could not get the thumbnail generator to even save a picture to the output file with out changing `[output_filepath]` to `"[output_filepath]"` with quotations. Once I added quotations I was able to at least see the thumbnail in the output file, however there is currently no way to view it in Mainsail. Hopefully you can update the docs to reflect this issue. 

Thanks.

**Comment by boweeble** [comment]
This is no longer an issue in Klipper/Mainsail and works just fine and thank you for the suggestion on the quotations.
