### ISSUE TITLE
Suggested offset for 2560x1440 & JyersUI compatibility

### ISSUE THREAD

**Issue by SiliconExarch** [boweeble/s3d-thumbnail-generator#3]
I've just started using this myself and would like to feed back what I've found to be the ideal offset when running the application maximised on a 1440p monitor - x=892 and y=132.

Currently the gcode files it produces aren't compatible with the gcode preview built into Jyers UI for the Ender 3 V2, however I've found that making them work is as easy as changing the comment at the start of the encoded jpeg data from `; thumbnail begin...` to `; jpeg thumbnail begin...`. With this in mind, would it be possible to add a command line option to insert a compatible header at some point in the future?

**Comment by JYCrois** [comment]
Good morning,
Can you explain to me the procedure to crop correctly?
where do i enter x=532 y=118 w=953 lw=400 lh=300 sw=32 sh=32?
Thanks in advance !

**Comment by boweeble** [comment]
> I've just started using this myself and would like to feed back what I've found to be the ideal offset when running the application maximised on a 1440p monitor - x=892 and y=132.
> 
> Currently the gcode files it produces aren't compatible with the gcode preview built into Jyers UI for the Ender 3 V2, however I've found that making them work is as easy as changing the comment at the start of the encoded jpeg data from `; thumbnail begin...` to `; jpeg thumbnail begin...`. With this in mind, would it be possible to add a command line option to insert a compatible header at some point in the future?

Thank you @SiliconExarch

**Comment by boweeble** [comment]
> > I've just started using this myself and would like to feed back what I've found to be the ideal offset when running the application maximised on a 1440p monitor - x=892 and y=132.
> > Currently the gcode files it produces aren't compatible with the gcode preview built into Jyers UI for the Ender 3 V2, however I've found that making them work is as easy as changing the comment at the start of the encoded jpeg data from `; thumbnail begin...` to `; jpeg thumbnail begin...`. With this in mind, would it be possible to add a command line option to insert a compatible header at some point in the future?
> 
> Thank you @SiliconExarch

This is done in the post processing section of your slicer. Below is a screenshot within the Simplify3D v5 post processing section.

![screenshot](https://user-images.githubusercontent.com/11066161/220718249-fa4a77cb-b678-4c9c-9116-875b924a32fe.PNG)
