### ISSUE TITLE
Can you explain to me the procedure to crop correctly

### ISSUE THREAD

**Issue by JYCrois** [boweeble/s3d-thumbnail-generator#4]
Good morning,
Can you explain to me the procedure to crop correctly?
where do i enter x=532 y=118 w=953 lw=400 lh=300 sw=32 sh=32?
Thanks in advance !

**Comment by boweeble** [comment]
This is done in the post processing section of your slicer.  Below is a screenshot within the Simplify3D v5 post processing section.

![screenshot](https://user-images.githubusercontent.com/11066161/220717098-a79560df-9e42-40af-a505-44174a7bd85f.PNG)

**Comment by JYCrois** [comment]
thank you for your reply

Best regards,

**Comment by boweeble** [comment]
> Good morning, Can you explain to me the procedure to crop correctly? where do i enter x=532 y=118 w=953 lw=400 lh=300 sw=32 sh=32? Thanks in advance !

It's a bit of trial and error, I've found the easiest way to determine the x & y coordinates for your setup is to take a screenshot then open the screenshot in an editor that gives you x/y position of your cursor which correlates to x=left, y=top of the image.  Hope this helps!

![Capture1](https://user-images.githubusercontent.com/11066161/220728590-6814c038-1041-4fbe-b310-c7e88f5c7eb5.PNG)
